port: 3000
logLevel: debug

misc:
  lockfile: maintenance.lock
  maintenanceNotification: null
  lastUpdateFile: .last-update
  changelogFile: CHANGELOG.md

url:
  basePath: http://localhost:3000
  apiPath: '/api'

swagger:
  path: /internal/docs
  title: Ibana Api
  description: REST Api
  useHttps: false

frontend:
  baseUrl: http://localhost:42069
  basePath: /

database:
  database: ibana-challenge
  host: localhost
  type: postgres
  port: 5430
  username: user
  password: secret
  cache: false
  keepConnectionAlive: true
  migrationsRun: false
  migrationsTableName: _migrations
  mock:
    database: _test
