version: '3.7'
services:
  db-postgresql:
    image: postgres:14-alpine
    env_file: ./.docker/db-postgresql/.env
    volumes:
      - ./.docker/db-postgresql/files/postgre-initialize.sh:/docker-entrypoint-initdb.d/postgre-initialize.sh:ro
    ports:
      - '5430:5432'
